### PR TITLE
RedisJSON support

### PR DESCRIPTION
**Pull request by vytskalt**
Added support for most RedisJSON commands.
@crackthecodeabhi it would be great if you reviewed this as soon as possible because I really need it in my project

### CODE REVIEW

**Comment by crackthecodeabhi** [comment]
@vytskalt Thanks for the contribution, that is great work! I will definitely, review and merge it ASAP.

Could you also add some test cases to cover the new commands, please.

**Comment by vytskalt** [comment]
> @vytskalt Thanks for the contribution, that is great work! I will definitely, review and merge it ASAP.
> 
> Could you also add some test cases to cover the new commands, please.

Sure, I just don't know how I would check if the Redis client has the JSON module

**Comment by vytskalt** [comment]
Tests are done. I just used the wiki examples

**Comment by crackthecodeabhi** [comment]
@vytskalt thank you, i am reviewing it and will be merging it by today.

**Review by crackthecodeabhi — APPROVED** [review]

**Comment by crackthecodeabhi** [comment]
merged and added CI test.
Released as minor patch to Maven implementation("io.github.crackthecodeabhi:kreds:0.7.1")

Thanks @vytskalt

**Pull request merged**
