### PR TITLE
Subscriber Authentication

### PR DESCRIPTION
**Pull request by rexlManu**
I tried to use the subscriber client with a redis instance thats password-protected and found out by #8 that authentication is missing.

### CODE REVIEW

**Comment by TomTruyen** [comment]
@crackthecodeabhi can you review this PR and make a patch release for it? I'm in desperate need for this for my project and Kreds would be perfect (for my current use case) if this feature was added. Thanks in advance :)

**Comment by rexlManu** [comment]
> @crackthecodeabhi can you review this PR and make a patch release for it? I'm in desperate need for this for my project and Kreds would be perfect (for my current use case) if this feature was added. Thanks in advance :)

You can download my fork and install it in your local maven repository, if you need it urgent. I think the author doesn't maintain it further.

**Comment by TomTruyen** [comment]
> > @crackthecodeabhi can you review this PR and make a patch release for it? I'm in desperate need for this for my project and Kreds would be perfect (for my current use case) if this feature was added. Thanks in advance :)
> 
> You can download my fork and install it in your local maven repository, if you need it urgent. I think the author doesn't maintain it further.

I have just been in contact with the author and he said the following:
`Yes, I will review and add some test cases to it before making a release. Should be done in a week.`

But I will probably do what you said until the new release is available

**Comment by crackthecodeabhi** [comment]
@rexlManu @TomTruyen will be reviewing and merging the issue ASAP. been busy lately. Give me sometime.

**Comment by JefCodes** [comment]
> @rexlManu @TomTruyen will be reviewing and merging the issue ASAP. been busy lately. Give me sometime.

Is there an ETA on this? The PubSub functionality is almost useless without it... I am stuck on project because of this issue

**Comment by crackthecodeabhi** [comment]
> > @rexlManu @TomTruyen will be reviewing and merging the issue ASAP. been busy lately. Give me sometime.
> 
> Is there an ETA on this? The PubSub functionality is almost useless without it... I am stuck on project because of this issue

There needs to be some work done on this PR, the current PR will cause a dead lock since the reader coroutine is not pre-empted before writing on the connection.

Will update as soon i fix it and run some tests.

**Comment by TomTruyen** [comment]
> > > @rexlManu @TomTruyen will be reviewing and merging the issue ASAP. been busy lately. Give me sometime.
> > 
> > 
> > Is there an ETA on this? The PubSub functionality is almost useless without it... I am stuck on project because of this issue
> 
> There needs to be some work done on this PR, the current PR will cause a dead lock since the reader coroutine is not pre-empted before writing on the connection.
> 
> Will update as soon i fix it and run some tests.

I didn't get a dead lock when using @rexlManu his version. Does the dead lock only happen in specific scenario's?

**Comment by rexlManu** [comment]
I'm currently using my version pretty much and didn't run in any issues. Maybe share a example where it occurs.

**Comment by crackthecodeabhi** [comment]
@rexlManu the subscriber coroutine suspends after it locks the mutex on the Konnection.
the Connection command interface which has now been added as implements to Subscriber Client,
will not preempt this corutine, before it takes a lock on the that connection mutex.

if the user subscribes to a channel, and then tries to execute any connection command, it will block indefinitely.

Hence, a clean approach would be to , accept optional auth parameters while building the subscriber client, and authenticate against redis before doing anything else, this ensure all other commands work as usual with no change.

**Comment by crackthecodeabhi** [comment]
> > > > @rexlManu @TomTruyen will be reviewing and merging the issue ASAP. been busy lately. Give me sometime.
> > > 
> > > 
> > > Is there an ETA on this? The PubSub functionality is almost useless without it... I am stuck on project because of this issue
> > 
> > 
> > There needs to be some work done on this PR, the current PR will cause a dead lock since the reader coroutine is not pre-empted before writing on the connection.
> > Will update as soon i fix it and run some tests.
> 
> I didn't get a dead lock when using @rexlManu his version. Does the dead lock only happen in specific scenario's?

After calling the subscribe command on the  subscriber client, call any other connection command, the coroutine will block

**Pull request closed without merging**
